### ISSUE TITLE
check-a-record fails to parse a host that contains 'http://' or a path

### ISSUE THREAD

**Issue by zankich** [cloudfoundry-incubator/check-a-record#6]
Given the url `http://httpstat.us`, I expected this to resolve, but instead it failed:
```
check-a-record http://httpstat.us
No A records found (lookup http://httpstat.us: invalid domain name)
```

This also throws a similar error:
```
check-a-record http://httpstat.us/502
No A records found (lookup http://httpstat.us/502: invalid domain name)
```

I would expect this to parse the base domain and check that.

**Comment by zankich** [comment]
cc @jaresty

**Comment by genevievelesperance** [comment]
Please see https://github.com/cloudfoundry-incubator/check-a-record/commit/4226f68599dc66aa6f3f7d9d7ef68afec90c35c1
